clusters:
- chartName: gitops-dev
  repoUrl: https://github.com/hello-world-gitops/gitops-dev.git
- chartName: gitops-hub
  repoUrl: https://github.com/hello-world-gitops/gitops-hub.git
# - chartName: gitops-stage
#   repoUrl: https://github.com/hello-world-gitops/gitops-stage.git
