{{ range .Values.clusters }}
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: {{ .chartName }}
  namespace: openshift-gitops
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - {{ .chartName }}
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  annotations:
    apps.open-cluster-management.io/reconcile-rate: medium
  name: {{ .chartName }}
  namespace: openshift-gitops
spec:
  type: Git
  pathname: "{{ .repoUrl }}"
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: main
    apps.open-cluster-management.io/git-path: '.'
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: {{ .chartName }}
  name: {{ .chartName }}
  namespace: openshift-gitops
spec:
  channel: "openshift-gitops/{{ .chartName }}"
  placement:
    placementRef:
      kind: PlacementRule
      name: {{ .chartName }}
  # If you don't have this packageOverrides section, the HelmRelease that is
  # created will error because the chartPath is set to "/tmp/<namespace>/<channel>-local".
  # Not sure if it's a bug or expected.
  packageOverrides:
    - packageName: {{ .chartName }}
      packageOverrides:
        - path: repo.source.git.chartPath
          value: '.'
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  labels:
    app: {{ .chartName }}
  name: {{ .chartName }}
  namespace: openshift-gitops
spec:
  clusterSelector:
    matchLabels:
      'local-cluster': 'true'
{{ end }}
